url: /insei          
# For Atom Feed
domain: /insei    
author: INSEI
email: m.steenhagen.09@ucl.ac.uk
title: INSEI

# standard jekyll configuration

permalink: /articles/:title
pygments: true
exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

markdown: rdiscount

github:
  username: msteenhagen

